name: FukumaiSummerFes
version: '${project.version}'
main: xyz.fukumaisaba.mc.fukumaisummerfes.SummerFesPlugin
api-version: 1.16
authors: [ FukumaiLAB ]
commands:
  voucher:
    description: 金券交換機能
depend:
  - Vault